"""initial tables

Revision ID: 6a4bd2e36415
Revises: 
Create Date: 2026-01-25 05:32:31.522891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a4bd2e36415'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('registration_code', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_code')
    )
    op.create_index(op.f('ix_fans_email'), 'fans', ['email'], unique=True)
    op.create_index(op.f('ix_fans_id'), 'fans', ['id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('artists', sa.Text(), nullable=False),
    sa.Column('ticket_limit', sa.Integer(), nullable=True),
    sa.Column('tickets_claimed', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_date'), 'tours', ['date'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('agreed_to_terms', sa.Boolean(), nullable=False),
    sa.Column('agreed_to_privacy', sa.Boolean(), nullable=False),
    sa.Column('agreed_to_marketing', sa.Boolean(), nullable=True),
    sa.Column('age_verified', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('confirmed_name', sa.String(length=200), nullable=False),
    sa.Column('confirmed_email', sa.String(length=255), nullable=False),
    sa.Column('confirmed_phone', sa.String(length=20), nullable=True),
    sa.Column('photo_id_path', sa.String(length=500), nullable=True),
    sa.Column('photo_id_uploaded', sa.Boolean(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.Column('signature_name', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('ticket_unlocked', sa.Boolean(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_fan_id'), 'consents', ['fan_id'], unique=True)
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_table('fan_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fan_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'EXPIRED', name='selectionstatus'), nullable=False),
    sa.Column('ticket_id', sa.String(length=100), nullable=True),
    sa.Column('ticket_qr_code', sa.String(length=500), nullable=True),
    sa.Column('ticket_pdf_path', sa.String(length=500), nullable=True),
    sa.Column('ticket_generated_at', sa.DateTime(), nullable=True),
    sa.Column('selected_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fan_id'], ['fans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_index(op.f('ix_fan_selections_fan_id'), 'fan_selections', ['fan_id'], unique=False)
    op.create_index(op.f('ix_fan_selections_id'), 'fan_selections', ['id'], unique=False)
    op.create_index(op.f('ix_fan_selections_tour_id'), 'fan_selections', ['tour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fan_selections_tour_id'), table_name='fan_selections')
    op.drop_index(op.f('ix_fan_selections_id'), table_name='fan_selections')
    op.drop_index(op.f('ix_fan_selections_fan_id'), table_name='fan_selections')
    op.drop_table('fan_selections')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_fan_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_date'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_fans_id'), table_name='fans')
    op.drop_index(op.f('ix_fans_email'), table_name='fans')
    op.drop_table('fans')
    # ### end Alembic commands ###
